name: unittests
on:
  push:
    branches:
      - master
jobs:
  py-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, py: "3.10" }
          - { os: windows-latest, py: "3.9" }
          - { os: windows-latest, py: "3.8" }
          - { os: macOS-latest, py: "3.10" }
          - { os: macOS-latest, py: "3.9" }
          - { os: macOS-latest, py: "3.8" }
          - { os: ubuntu-latest, py: "3.10" }
          - { os: ubuntu-latest, py: "3.9" }
          - { os: ubuntu-latest, py: "3.8" }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytype
      - name: LOAD EE CREDENTIALS
        run: python ./.github/ee_token.py
        env:
          EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      - name: UNIT TESTS
        run: |
          pytest -v
      - name: TYPE CHECKING
        run: |
          pytype -j auto
